Add Makefile for development shortcuts
valohai/valohai-yaml pull request #109
Opened 2023-08-16 11:51 UTC by teroyks

Resolves #108

Use standard commands (dev, lint, test) for development – reduces the need to check the README for repository-specific commands.

2023-08-16 11:57 UTC, teroyks commented
I was thinking that if we wanted, we could add some extra features to the makefiles, such as:

- optional tests parameter for `make test`
- linting only the changed files

However, this repository is so small that linting and testing all the files is very quick, so perhaps that is more trouble than it is worth.

2023-08-17 05:37 UTC, ruksi requested changes

2023-08-17 05:37 UTC, ruksi commented on Makefile
> +.PHONE: test
:telephone_receiver:

2023-08-17 05:51 UTC, teroyks commented on Makefile
> +.PHONE: test
What phone? I see no phone! 🙂 
(pushed a fixup commit)

2023-08-17 05:59 UTC, ruksi approved these changes
> I was thinking that if we wanted, we could add some extra features to the makefiles, such as:
> 
> * optional tests parameter for `make test`
> * linting only the changed files
> 
> However, this repository is so small that linting and testing all the files is very quick, so perhaps that is more trouble than it is worth.

yeah, I'd like to make that you could type `make test -- path/to/files` or something which would just run those specific tests / lints but I haven't hand the willpower to check if it would even be possible without `$VARIABLES` :P

for the lint, my personal syntax preference would be `make lint.changed` but dunno what we collectively land on :thinking: 

and probably not worth for this repository :+1:

2023-08-17 05:59 UTC, merged