Add continue-on-error boolean to Pipeline Nodes
valohai/valohai-yaml pull request #65
Opened 2022-02-07 12:14 UTC by tokkoro

Add optional continue-on-error boolean to each node for https://github.com/valohai/roi/issues/3577

2022-02-07 12:16 UTC, akx requested changes
Type question.

2022-02-07 12:16 UTC, akx commented on valohai_yaml/objs/pipelines/deployment_node.py
> +        continue_on_error: Optional[bool] = False,
The value can't be true/false/none, can it?

```suggestion
        continue_on_error: bool = False,
```

2022-02-07 12:16 UTC, akx commented on valohai_yaml/objs/pipelines/execution_node.py
> +        continue_on_error: Optional[bool] = False,
```suggestion
        continue_on_error: bool = False,
```

2022-02-07 12:16 UTC, akx commented on valohai_yaml/objs/pipelines/node.py
> +        continue_on_error: Optional[bool] = False
```suggestion
        continue_on_error: bool = False
```

2022-02-07 12:24 UTC, akx approved these changes

2022-02-09 12:54 UTC, tokkoro commented
Closing this as #66 will override it.

2022-02-09 12:54 UTC, closed without merging