Add on-error enum string to Pipeline Nodes
valohai/valohai-yaml pull request #66
Opened 2022-02-08 11:15 UTC by tokkoro

I was thorn if this setting should be a `boolean` or `enum`. After more discussion this morning, I see that in near future we might have `on-error: "stop-next"` and `on-error: "retry"`. 

The current behavior when error happens is that all other non finished nodes are stopped, so the default value for `on-error` is "stop-all" and the new option that doesn't care about errors is "continue".

This will replace https://github.com/valohai/valohai-yaml/pull/65

2022-02-08 11:28 UTC, akx requested changes
`on_error` is definitely better than the boolean. Could you make the value an Enum, though, instead of an open-ended string?

2022-02-08 11:28 UTC, akx commented on valohai_yaml/objs/pipelines/node.py
> +    on_error: str
I think the in-memory representation for this should be an Enum, like `KeepDirectories` and `MultipleMode` are.

2022-02-10 08:20 UTC, tokkoro commented
Now Roi's api of `GET /api/v0/commits/[HASH]/?include=config` returns a config where the `on_error` keys are `on-error`. So it doesn't change the kebab-case into snake_case. I see the conversion in Item.parse() and tried to add ` data['on_error'] = data.pop('on-error')` into `Node.parse_qualifying`  but I don't know where it should happen. Any pointers where to look @akx ?

2022-02-10 09:32 UTC, akx commented
@tokkoro I don't think it _should_ change it into snake case, since the serialization is basically the YAML representation.

2022-02-10 13:07 UTC, tokkoro commented
Yes, I was thinking something about some unrelated data transformation down the line that are out of valohai-yaml scope. I fixed the import sorting errors and I think we are good to go in current state.

2022-02-11 11:41 UTC, akx requested changes

2022-02-11 11:41 UTC, akx commented on valohai_yaml/schema/deployment-node.yaml
> +    enum: ["stop-all", "continue"]
Seems `ErrorAction.STOP_NEXT` isn't represented here? (Maybe add a test for it?)
```suggestion
    enum: ["stop-all", "stop-next", "continue"]
```

2022-02-11 11:41 UTC, akx commented on valohai_yaml/schema/execution-node.yaml
> +    enum: ["stop-all", "continue"]
Seems `ErrorAction.STOP_NEXT` isn't represented here? (Maybe add a test for it?)
```suggestion
    enum: ["stop-all", "stop-next", "continue"]
```

2022-02-11 11:41 UTC, akx commented on valohai_yaml/schema/task-node.yaml
> +    enum: ["stop-all", "continue"]
Seems `ErrorAction.STOP_NEXT` isn't represented here? (Maybe add a test for it?)
```suggestion
    enum: ["stop-all", "stop-next", "continue"]
```

2022-02-14 07:33 UTC, akx approved these changes

2022-02-14 07:37 UTC, merged